#!/usr/bin/env bash
# DexHub Build-Instructions (E2.3)
#
# Zweck: Compile Step — baut platform-native Instruction-Files aus SSOT.
# Input:  .dexCore/core/instructions/{SHARED,claude-specific,copilot-specific}.md
# Output: .github/copilot-instructions.md  (concatenation-based)
#         .claude/CLAUDE.md                 (@import-based, wenn Claude-native @import funktioniert)
#
# Modes:
#   build     — regenerate outputs (default)
#   check     — drift check only (exit 1 if outputs are stale)
#   dry-run   — show what would be built, no writes
#
# Usage:
#   ./.dexCore/_dev/tools/build-instructions.sh           # build
#   ./.dexCore/_dev/tools/build-instructions.sh check     # drift check (for CI/pre-commit)
#   ./.dexCore/_dev/tools/build-instructions.sh dry-run   # preview

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

SHARED="$REPO_ROOT/.dexCore/core/instructions/SHARED.md"
CLAUDE_TAIL="$REPO_ROOT/.dexCore/core/instructions/claude-specific.md"
COPILOT_TAIL="$REPO_ROOT/.dexCore/core/instructions/copilot-specific.md"

COPILOT_OUT="$REPO_ROOT/.github/copilot-instructions.md"
CLAUDE_OUT="$REPO_ROOT/.claude/CLAUDE.md"

MODE="${1:-build}"

# --- Validation ---
validate_inputs() {
  for f in "$SHARED" "$CLAUDE_TAIL" "$COPILOT_TAIL"; do
    if [ ! -f "$f" ]; then
      echo "FAIL: Source file missing: $f"
      exit 2
    fi
    if [ ! -s "$f" ]; then
      echo "FAIL: Source file empty: $f"
      exit 2
    fi
  done
}

# --- Copilot Build (concatenation) ---
build_copilot() {
  local target="$1"
  mkdir -p "$(dirname "$target")"

  {
    echo "# GitHub Copilot Instructions for DexHub"
    echo ""
    echo "<!-- AUTOGENERATED from .dexCore/core/instructions/SHARED.md + copilot-specific.md. -->"
    echo "<!-- Do not edit directly. Edit the sources and run build-instructions.sh. -->"
    echo "<!-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
    echo ""
    cat "$SHARED"
    echo ""
    cat "$COPILOT_TAIL"
  } > "$target"
}

# --- Claude Build (concatenation fallback — @import would be native alternative) ---
# Note: Until A/B-Test for @import is green, we concatenate for Claude too (safer default).
# When A/B-Test passes, switch Claude output to @import-based .claude/CLAUDE.md
# that references SHARED.md + claude-specific.md.
build_claude_concat() {
  local target="$1"
  mkdir -p "$(dirname "$target")"

  {
    echo "# DexHub Enterprise - Claude Code Instructions"
    echo ""
    echo "<!-- AUTOGENERATED from .dexCore/core/instructions/SHARED.md + claude-specific.md. -->"
    echo "<!-- Do not edit directly. Edit the sources and run build-instructions.sh. -->"
    echo "<!-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
    echo ""
    cat "$SHARED"
    echo ""
    cat "$CLAUDE_TAIL"
  } > "$target"
}

# Note: @import-based Claude output (requires Claude A/B test pass):
# build_claude_import() {
#   cat > "$CLAUDE_OUT" <<EOF
# # DexHub Claude Code Instructions (via native @import)
# @../.dexCore/core/instructions/SHARED.md
# @../.dexCore/core/instructions/claude-specific.md
# EOF
# }

# --- Compute hash of generated content ---
# Strips the "Generated:" header comment line so the hash is stable.
content_hash() {
  local file="$1"
  [ -f "$file" ] || { echo ""; return; }
  grep -v '<!-- Generated:' "$file" | shasum -a 256 | cut -d' ' -f1
}

# --- Compute expected hash from sources ---
expected_hash_copilot() {
  {
    echo "# GitHub Copilot Instructions for DexHub"
    echo ""
    echo "<!-- AUTOGENERATED from .dexCore/core/instructions/SHARED.md + copilot-specific.md. -->"
    echo "<!-- Do not edit directly. Edit the sources and run build-instructions.sh. -->"
    echo ""
    cat "$SHARED"
    echo ""
    cat "$COPILOT_TAIL"
  } | shasum -a 256 | cut -d' ' -f1
}

expected_hash_claude() {
  {
    echo "# DexHub Enterprise - Claude Code Instructions"
    echo ""
    echo "<!-- AUTOGENERATED from .dexCore/core/instructions/SHARED.md + claude-specific.md. -->"
    echo "<!-- Do not edit directly. Edit the sources and run build-instructions.sh. -->"
    echo ""
    cat "$SHARED"
    echo ""
    cat "$CLAUDE_TAIL"
  } | shasum -a 256 | cut -d' ' -f1
}

# --- Main ---
case "$MODE" in
  dry-run)
    validate_inputs
    echo "=== DRY RUN ==="
    echo "Sources:"
    echo "  $SHARED ($(wc -l < "$SHARED") lines)"
    echo "  $CLAUDE_TAIL ($(wc -l < "$CLAUDE_TAIL") lines)"
    echo "  $COPILOT_TAIL ($(wc -l < "$COPILOT_TAIL") lines)"
    echo ""
    echo "Would write:"
    echo "  $COPILOT_OUT"
    echo "  $CLAUDE_OUT"
    echo ""
    echo "Expected Copilot content hash: $(expected_hash_copilot)"
    echo "Expected Claude content hash:  $(expected_hash_claude)"
    ;;

  check)
    validate_inputs
    DRIFT=0

    if [ ! -f "$COPILOT_OUT" ]; then
      echo "FAIL: $COPILOT_OUT missing"
      DRIFT=1
    else
      ACTUAL=$(content_hash "$COPILOT_OUT")
      EXPECTED=$(expected_hash_copilot)
      if [ "$ACTUAL" != "$EXPECTED" ]; then
        echo "DRIFT: $COPILOT_OUT is out of sync with sources"
        echo "  actual:   $ACTUAL"
        echo "  expected: $EXPECTED"
        DRIFT=1
      fi
    fi

    if [ ! -f "$CLAUDE_OUT" ]; then
      echo "FAIL: $CLAUDE_OUT missing"
      DRIFT=1
    else
      ACTUAL=$(content_hash "$CLAUDE_OUT")
      EXPECTED=$(expected_hash_claude)
      if [ "$ACTUAL" != "$EXPECTED" ]; then
        echo "DRIFT: $CLAUDE_OUT is out of sync with sources"
        echo "  actual:   $ACTUAL"
        echo "  expected: $EXPECTED"
        DRIFT=1
      fi
    fi

    if [ $DRIFT -eq 0 ]; then
      echo "OK: all generated instruction files are in sync with sources"
      exit 0
    else
      echo ""
      echo "Run: ./.dexCore/_dev/tools/build-instructions.sh"
      exit 1
    fi
    ;;

  build)
    validate_inputs
    echo "=== Build Instructions ==="
    build_copilot "$COPILOT_OUT"
    echo "OK: $COPILOT_OUT ($(wc -l < "$COPILOT_OUT") lines)"
    build_claude_concat "$CLAUDE_OUT"
    echo "OK: $CLAUDE_OUT ($(wc -l < "$CLAUDE_OUT") lines)"
    echo ""
    echo "Note: Claude uses concatenation (safe default). Switch to @import-based"
    echo "      build only after the A/B @import test passes (see A_B_TEST_IMPORT_PROCEDURE)."
    ;;

  *)
    echo "Usage: $0 [build|check|dry-run]"
    exit 2
    ;;
esac
